# Generated by Django 3.0.5 on 2020-04-18 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_stock_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='date',
        ),
    ]
