# Generated by Django 3.0.5 on 2020-04-18 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_stock_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stock',
            options={'ordering': ['create_date'], 'verbose_name': 'Stock', 'verbose_name_plural': 'Stocks'},
        ),
        migrations.AddField(
            model_name='stock',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='stocks'),
        ),
    ]
