# Generated by Django 3.0.5 on 2020-04-18 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20200418_1553'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stock',
            options={'ordering': ['-create_date'], 'verbose_name': 'Stock', 'verbose_name_plural': 'Stocks'},
        ),
    ]
