# Generated by Django 3.0.5 on 2020-04-18 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_stock_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='stocks/', verbose_name='Photo')),
            ],
        ),
        migrations.RemoveField(
            model_name='stock',
            name='image',
        ),
        migrations.AddField(
            model_name='stock',
            name='image',
            field=models.ManyToManyField(to='main.Photo'),
        ),
    ]
