# Generated by Django 3.0.5 on 2020-04-18 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20200418_1854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='file',
            field=models.ImageField(upload_to='stocks/', verbose_name='Photo'),
        ),
    ]
