# Generated by Django 3.0.5 on 2020-06-16 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20200418_1902'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('price', models.PositiveIntegerField()),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('last_mod', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'ordering': ['-create_date'],
            },
        ),
        migrations.RemoveField(
            model_name='stock',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='energy_class',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='image',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='model',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='note',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='price',
        ),
        migrations.AddField(
            model_name='stock',
            name='quantity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Photo',
        ),
    ]
