# Generated by Django 3.0.5 on 2020-06-27 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_auto_20200620_1658'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stock',
            options={'ordering': ['-last_mod'], 'verbose_name': 'Stock', 'verbose_name_plural': 'Stocks'},
        ),
    ]
