# Generated by Django 3.0.5 on 2020-07-02 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_auto_20200628_1508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipt',
            name='description',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
