# Generated by Django 3.0.5 on 2020-07-25 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_auto_20200702_1506'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bon_number', models.CharField(max_length=100)),
                ('price', models.FloatField()),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
        migrations.AlterModelOptions(
            name='recipt',
            options={'ordering': ['-create_date']},
        ),
        migrations.AlterModelOptions(
            name='shift',
            options={'ordering': ['-date']},
        ),
        migrations.AddField(
            model_name='recipt',
            name='image',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
